version: "3.7"
services:
  relaym-server:
    image: registry.camph.net/relaym-server-prod:latest
    container_name: relaym-server-prod
    networks:
      - microservices

networks:
  microservices:
    external: true
