version: "3.7"
services:
  relaym-server:
    image: registry.camph.net/relaym-server-dev:latest
    container_name: relaym-server-dev
    networks:
      - microservices
networks:
  microservices:
    external: true
