name: Deploy dev environment

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
    - 'docs/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KONOE_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KONOE_KNOWN_HOSTS }}
      - name: Setup docker context
        run: |
          docker context create --default-stack-orchestrator=swarm --docker "host=ssh://${{ secrets.KONOE_SSH_USERNAME }}@${{ secrets.KONOE_SSH_HOST }}:${{ secrets.KONOE_SSH_PORT }}" konoe
          docker context use konoe
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: registry.camph.net
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Check out
        uses: actions/checkout@v1
      - name: Deploy
        run: |
          make deploy-dev-from-github-action
      - name: Notify to Slack
        uses: craftech-io/slack-action@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
