name: test_and_static_analysis

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'master'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: |
        go mod download

    - name: set up mysql
      run: |
        make run-db-local
        sleep 20 #mysql立ち上げ待ち

    - name: Get tools
      run: |
        GO111MODULE=off go get -u github.com/skeema/skeema
        export PATH=$PATH:$(go env GOPATH)/bin

    - name: migrate
      run: |
        $(go env GOPATH)/bin/skeema push local

    - name: Build
      run: go build -v .

    - name: Test
      run: make test
