name: test_and_lint

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
    - 'docs/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.18
      uses: actions/setup-go@v3.2.0
      with:
        go-version: 1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Restore cache
      uses: actions/cache@v3.2.5
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: |
        go mod download

    - name: set up mysql
      run: |
        make run-db-local
        eval "$(cat env.local <(echo) <(declare -x))"
        until mysql -u${DB_USER} -p${DB_PASSWORD} -h${DB_HOST} -P${DB_PORT} -e "SELECT 1"; do sleep 1; done

    - name: Get tools
      run: |
        make tools

    - name: migrate
      run: |
        $(go env GOPATH)/bin/skeema push local

    - name: Build
      run: go build -v .

    - name: Test
      run: make test-with-coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./profile.out

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          args: --enable=gosec,prealloc,gocognit
